name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7
      - name: Deploy with Maven to GitHub Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The GITHUB_REF tag comes in the format 'refs/tags/vxxx'.
        # So if we remove everything before the last '/v', we can get the release version.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | sed -r 's/.*\/v//')
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          mvn -B versions:set -DnewVersion=${NEW_VERSION}
          mvn -B versions:commit
          mvn -B install --file pom.xml
          mvn -B assembly:single --file cactus-assembly pom.xml
          mvn -B deploy --file pom.xml